version: 2
jobs:
    process-and-publish:
        machine: true
        steps:
            - run:
                # Récupération du code manuel car soucis avec "- checkout"
                name: Récupération de decp-rama
                command: |
                    mkdir -p /home/circleci/project
                    cd /home/circleci/project
                    git clone https://github.com/etalab/decp-rama
                    cd decp-rama
                    git checkout $CIRCLE_BRANCH

            - run:
                name: Installation des dépendances
                command: |
                    sudo apt install -y jq xsltproc libxml2-utils
                    cd /home/circleci/project
                    git clone https://github.com/Cheedoong/xml2json.git
                    cd xml2json
                    make

            - run:
                name: Récupération et traitement des données
                command: |
                     cd /home/circleci/project/decp-rama
                     export PATH=$PATH:/home/circleci/project/xml2json
                     ./process.sh all package sequence
            - run:
                name: Fusion de tous les fichiers de source en un seul
                command: |
                    cd /home/circleci/project/decp-rama
                    ./merge_all_sources.sh
            - run:
                name: Conversion du JSON agrégé en XML
                command: |
                    cd /home/circleci/project/decp-rama
                    mkdir xml
                    git clone https://github.com/edsu/json2xml.git ../json2xml
                    export PATH=$PATH:/home/circleci/project/json2xml
                    scripts/jsonDECP2xmlDECP.sh json/decp.json > xml/decp.xml

            - run:
                name: Publication des données sur (next.)data.gouv.fr
                command: |
                    cd /home/circleci/project/decp-rama
                    ./publish.sh
workflows:
    version: 2
    dev:
        jobs:
            - process-and-publish:
                filters:
                    branches:
                        only:
                            - develop
    daily:
        jobs:
            - process-and-publish
        triggers:
            - schedule:
                cron: 0 4 * * *
                filters:
                    branches:
                        only:
                            - master
