---
version: 2
jobs:
    process:
        docker:
            - image: 139bercy/decp-rama
        steps:
            - checkout
            - run: date +%F > date
            - run:
                name: Récupération et traitement des données
                no_output_timeout: 6h
                command: |
                     ./process.sh all package sequence
            - save_cache:
                key: data-out-{{ .Branch }}-{{ checksum "date" }}
                paths:
                  - "json/decp.json"
                  - "xml/decp.xml"
                  - "decp_*.json"
                  - "decp_*.xml"
                  - "json/decp.ocds.json"
            # - run:
            #       name: Publication des données sur (next.)data.gouv.fr
            #       command: |
            #           ./publish-decp.sh
    publish:
      docker:
        - image: 139bercy/decp-rama
      steps:
        - checkout
        - run: date +%F > date
        - restore_cache:
            keys:
              - data-out-{{ .Branch }}-{{ checksum "date" }}
        - run:
            name: Publication des données sur (next.)data.gouv.fr
            command: |
                ./publish-decp.sh
workflows:
    version: 2
    dev:
      jobs:
          - process
    daily:
      jobs:
        - process
        - publish:
            context:
              - decp-rama-context
            requires:
              - process
      triggers:
        - schedule:
            cron: 0 3 * * 2,3,4,5,6
            filters:
              branches:
                only:
                  - master
