from .AifeProcess import AifeProcess
from .Aife2024Process import Aife2024Process
from .Atexo2024Process import Atexo2024Process
from .AwsProcess import AwsProcess
from .Aws2024Process import Aws2024Process
from .BfcProcess import BfcProcess
from .BreProcess import BreProcess
from .DecpAwsProcess import DecpAwsProcess
from .EmarProcess import EmarProcess
from .Emar2024Process import Emar2024Process
from .LyonProcess import LyonProcess
from .MaxiProcess import MaxiProcess
from .MegaProcess import MegaProcess
from .Megalis2024Process import Megalis2024Process
from .PesProcess import PesProcess
from .Pes2024Process import Pes2024Process
from .Ppsmj2024Process import Ppsmj2024Process
from .SampleXmlProcess import SampleXmlProcess
from .SampleJsonProcess import SampleJsonProcess
from .Xmarches2024Process import Xmarches2024Process