from .AifeProcess import AifeProcess
from .Aife2024Process import Aife2024Process
from .Atexo2024Process import Atexo2024Process
from .AwsProcess import AwsProcess
from .Aws2024Process import Aws2024Process
from .BfcProcess import BfcProcess
from .BreProcess import BreProcess
from .DecpAwsProcess import DecpAwsProcess
from .EmarProcess import EmarProcess
from .Emar2024Process import Emar2024Process
from .LyonProcess import LyonProcess
from .MaxiProcess import MaxiProcess
from .MegaProcess import MegaProcess
from .Megalis2024Process import Megalis2024Process
from .PesProcess import PesProcess
from .Modula2024Process import Modula2024Process
from .Pes2024Process import Pes2024Process
from .Ppsmj2024Process import Ppsmj2024Process
from .DemoApiProcess import DemoApiProcess
from .SampleXmlProcess import SampleXmlProcess
from .SampleJsonProcess import SampleJsonProcess
from .Xmarches2024Process import Xmarches2024Process
from .Modulademat2024Process import Modulademat2024Process
from .EuroStrasbourgProcess import EuroStrasbourgProcess
from .VilleStrasbourgProcess import VilleStrasbourgProcess
from .Medialex2024Process import Medialex2024Process
#=
#from .Proxilegales2024Process import Proxilegales2024Process
#from .Achatspublicscorse2024Process import Achatspublicscorse2024Process
#from .Marchespublicspro2024Process import Marchespublicspro2024Process
#from .Provencecorse2024Process import Provencecorse2024Process
#from .Antilleslegales2024Process import Antilleslegales2024Process
#from .Marchedemat2024Process import Marchedemat2024Process
